DROP DATABASE IF EXISTS TDW_PROGETTO;
CREATE DATABASE TDW_PROGETTO;
USE TDW_PROGETTO;


/*--------------------- TABLE ---------------------*/

CREATE TABLE `UTENTE` (
    `ID` INT AUTO_INCREMENT PRIMARY KEY,
    `NOME` VARCHAR(100) NOT NULL,
    `COGNOME` VARCHAR(100) NOT NULL,
    `EMAIL` VARCHAR(100) NOT NULL,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `RUOLO` ENUM('UTENTE', 'AMMINISTRATORE'),
    UNIQUE (`EMAIL`)
);

CREATE TABLE `PRODUTTORE`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
	`NOME` VARCHAR(100) NOT NULL
);

CREATE TABLE `PAGAMENTO`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
	`NOME` VARCHAR(100) NOT NULL
);

CREATE TABLE `SPEDIZIONE`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
	`NOME` VARCHAR(100) NOT NULL,
    `PREZZO` DOUBLE NOT NULL
);

CREATE TABLE `CATEGORIA`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
	`NOME` ENUM('T-SHIRT','PANTS','JEANS','SWEATSHIRT','SHIRT', 'JACKET','ACCESSORIES')
);


CREATE TABLE `SESSO`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
	`SESSO` ENUM('MAN','WOMAN','KIDS')
);



CREATE TABLE `TAGLIA`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
    `TAGLIA` ENUM('XS','S','M','L','XL','2XL')
);



CREATE TABLE `PRODOTTO`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
    `NOME` VARCHAR(256) NOT NULL,
    `PREZZO` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `DESCRIZIONE` TEXT NOT NULL,
	`ID_PRODUTTORE` INT DEFAULT NULL,
    `ID_CATEGORIA` INT NOT NULL,
    `ID_SESSO` INT NOT NULL,
	FOREIGN KEY (`ID_PRODUTTORE`) REFERENCES `PRODUTTORE`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (`ID_CATEGORIA`) REFERENCES `CATEGORIA`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`ID_SESSO`) REFERENCES `SESSO`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);




CREATE TABLE `COLORE`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
    `COLORE` ENUM('BLACK','WHITE','RED','BLUE','PINK','YELLOW','ORANGE','GREEN','PURPLE','BROWN','GRAY','BEIGE')
);



CREATE TABLE `ARTICOLO`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
    `ID_PRODOTTO` INT NOT NULL,
    `ID_TAGLIA` INT NOT NULL,
    `ID_COLORE` INT NOT NULL,
	`QUANTITA` INT NOT NULL DEFAULT 0,
    FOREIGN KEY (`ID_PRODOTTO`) REFERENCES `PRODOTTO`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`ID_TAGLIA`) REFERENCES `TAGLIA`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`ID_COLORE`) REFERENCES `COLORE`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);



CREATE TABLE `IMMAGINE`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
    `NOME` VARCHAR(128) NOT NULL,
    `PATH` VARCHAR(512) NOT NULL,
	`ID_PRODOTTO` INT NOT NULL,
	FOREIGN KEY (`ID_PRODOTTO`) REFERENCES `PRODOTTO`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);



CREATE TABLE `CARATTERISTICA`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
    `NOME` VARCHAR(128) NOT NULL
);




CREATE TABLE `CARATTERISTICA_PRODOTTO`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
    `ID_PRODOTTO` INT NOT NULL,
    `ID_CARATTERISTICA` INT NOT NULL,
    `TESTO` TEXT NOT NULL,
	FOREIGN KEY (`ID_PRODOTTO`) REFERENCES `PRODOTTO`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`ID_CARATTERISTICA`) REFERENCES `CARATTERISTICA`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `CARRELLO`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
    `ID_UTENTE` INT NOT NULL UNIQUE,
    FOREIGN KEY (`ID_UTENTE`) REFERENCES `UTENTE`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `ITEM_CARRELLO`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
    `ID_CARRELLO` INT NOT NULL,
    `ID_ARTICOLO` INT NOT NULL,
    FOREIGN KEY (`ID_CARRELLO`) REFERENCES `CARRELLO`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`ID_ARTICOLO`) REFERENCES `ARTICOLO`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);



CREATE TABLE `LISTA_DESIDERI`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
    `ID_UTENTE` INT NOT NULL,
    FOREIGN KEY (`ID_UTENTE`) REFERENCES `UTENTE`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE `ITEM_LISTA_DESIDERI`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
    `ID_LISTA_DESIDERI` INT NOT NULL,
    `ID_ARTICOLO` INT NOT NULL,
    FOREIGN KEY (`ID_LISTA_DESIDERI`) REFERENCES `LISTA_DESIDERI`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`ID_ARTICOLO`) REFERENCES `ARTICOLO`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE(`ID_LISTA_DESIDERI`,`ID_ARTICOLO`)
);



CREATE TABLE `NOTIFICA`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
    `OGGETTO` VARCHAR(256) NOT NULL,
    `TESTO` TEXT NOT NULL,
    `STATO` ENUM("CHIUSA","APERTA") NOT NULL DEFAULT "CHIUSA", 
    `ID_UTENTE` INT NOT NULL,
    `DATE` DATE DEFAULT (CURRENT_DATE),
    FOREIGN KEY (`ID_UTENTE`) REFERENCES `UTENTE`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `ORDINE`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
    `DATA_ORDINE` DATE DEFAULT (CURRENT_DATE),
    `DATA_ARRIVO` DATE NOT NULL,
    `PREZZO` DOUBLE NOT NULL DEFAULT 0.0,
    `INDIRIZZO_CONSEGNA` VARCHAR(256) NOT NULL,
    `STATO` ENUM("IN_LAVORAZIONE","SPEDITO") DEFAULT "IN_LAVORAZIONE",
    `ID_UTENTE` INT NOT NULL,
    `ID_PAGAMENTO` INT NOT NULL,
    `ID_SPEDIZIONE` INT NOT NULL,
    FOREIGN KEY (`ID_UTENTE`) REFERENCES `UTENTE`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`ID_PAGAMENTO`) REFERENCES `PAGAMENTO`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (`ID_SPEDIZIONE`) REFERENCES `SPEDIZIONE`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `ORDINE_ARTICOLO`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
    `ID_ARTICOLO` INT NOT NULL,
    `ID_ORDINE` INT NOT NULL,
    FOREIGN KEY (`ID_ARTICOLO`) REFERENCES `ARTICOLO`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`ID_ORDINE`) REFERENCES `ORDINE`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `RECENSIONE`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
    `TESTO` TEXT NOT NULL,
    `ID_PRODOTTO` INT NOT NULL,
    `ID_UTENTE` INT NOT NULL,
    `DATE` DATE DEFAULT (CURRENT_DATE),
    FOREIGN KEY (`ID_PRODOTTO`) REFERENCES `PRODOTTO`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`ID_UTENTE`) REFERENCES `UTENTE`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `VALUTAZIONE`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
    `STELLE` INT NOT NULL,
    `ID_PRODOTTO` INT NOT NULL,
    `ID_UTENTE` INT NOT NULL,
    FOREIGN KEY (`ID_PRODOTTO`) REFERENCES `PRODOTTO`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`ID_UTENTE`) REFERENCES `UTENTE`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CHECK( 0 <= `STELLE` AND `STELLE` <= 5) 
);


/*--------------------- VIEW ---------------------*/
CREATE VIEW ARTICOLO_PRODOTTO AS SELECT 
A.ID AS ID_ARTICOLO, A.ID_TAGLIA AS ID_TAGLIA, A.ID_COLORE AS ID_COLORE, A.QUANTITA AS QUANTITA,
P.ID AS ID_PRODOTTO, P.NOME AS NOME_PRODOTTO, P.ID_CATEGORIA AS ID_CATEGORIA, P.ID_PRODUTTORE AS ID_PRODUTTORE FROM
ARTICOLO AS A JOIN PRODOTTO AS P ON P.ID = A.ID_PRODOTTO;



